# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config)

1.21.5
<function show at 0x0000024183D17EE0>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
s = np.zeros(10)
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
s = np.zeros((3,5))
print("%d bytes" % (s.size * s.itemsize))

120 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
s = np.zeros(10)
print(s)
print("Updated fifth value is")
s[4] = 1
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated fifth value is
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
s = np.arange(10,49)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
s = np.arange(10,49)
print("the original vector is:")
print(s)
s = s[::-1]
print("the reverse vector is:")
print(s)

the original vector is:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
the reverse vector is:
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
s = np.arange(0,9).reshape(3,3)
print(s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
s = np.array([1,2,0,0,4,0])
ss = np.nonzero(s)
print(ss)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
s = np.eye(3,3)
print(s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
s = np.random.random((3,3,3))
print(s)

[[[0.78705136 0.8233077  0.98430749]
  [0.92705114 0.67851024 0.06049382]
  [0.272672   0.67342845 0.77925531]]

 [[0.77262169 0.0959167  0.35200588]
  [0.55067626 0.33877039 0.02058426]
  [0.87071142 0.35672028 0.46851908]]

 [[0.90783956 0.0287613  0.52693965]
  [0.71202137 0.79502136 0.91861887]
  [0.47912889 0.52077995 0.86287253]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
s = np.random.random((10,10))
print("random values are:")
print(s)
smax, smin = (s.max(), s.min())
print("maximum random value is:")
print(smax)
print("minimum random value is:")
print(smin)

random values are:
[[0.37008548 0.14799439 0.35696933 0.11715649 0.41885783 0.53436441
  0.23273599 0.96419142 0.93395364 0.6430999 ]
 [0.80947164 0.75018338 0.26626696 0.66407586 0.151483   0.36533166
  0.06119214 0.77183537 0.38375596 0.98546287]
 [0.91857778 0.98252695 0.02597248 0.18203303 0.77920539 0.89991635
  0.01928894 0.26025245 0.47419841 0.34038913]
 [0.02180717 0.99309134 0.35133534 0.11280463 0.67123297 0.61273243
  0.57755015 0.1874192  0.2574614  0.19129269]
 [0.45821233 0.27390193 0.13935121 0.44563123 0.89755246 0.79266952
  0.493557   0.87276672 0.24426191 0.63984892]
 [0.55845731 0.09915818 0.31264287 0.22914453 0.88804558 0.89360901
  0.50837867 0.72615593 0.45823683 0.92801713]
 [0.49411427 0.1829662  0.83170061 0.00890063 0.93524468 0.63473402
  0.33307287 0.168224   0.73242859 0.3720256 ]
 [0.53346164 0.54516531 0.67439203 0.09432524 0.21739239 0.36423168
  0.39381425 0.51652413 0.86923396 0.10401378]
 [0.16838734 0.72505194 0.61712008 0.38886418 0.37089444 0.69

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
s = np.random.random(30)
j = s.mean()
print(j)

0.5340671799904193


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
s = np.ones((4,4))
s[1:-1,1:-1] = 0
print(s)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
s = np.ones((6,6))
s = np.pad(s, pad_width=1, mode='constant', constant_values=0)
print(s)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
s = np.diag(1+np.arange(4),k=-1)
print(s)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
s = np.zeros((8,8),dtype=int)
s[1::2,::2] = 1
s[::2,1::2] = 1
print(s)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
s = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(s)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
a = np.random.random((5,5))
amax,amin = a.max(),a.min()
a = (a - amin)/(amax-amin)
print(a)


[[0.36603101 0.76074033 0.06935164 0.65456862 0.67278649]
 [0.91511286 0.74868112 0.62734466 0.04383185 0.48829021]
 [0.34319348 0.14182436 0.45640984 0.70030338 0.51211093]
 [0.42314748 0.88735572 0.13200031 0.23057232 1.        ]
 [0.19572125 0.95359964 0.43667589 0.98847869 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
s = np.arange(15).reshape((5, 3))
r = np.arange(6).reshape((3, 2))
np.dot(s, r)


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [25]:
j = np.ones((5,3)) @ np.ones((3,2))
print(j)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [26]:
s = np.arange(11)
s[(3 < s) & (s <= 8)] = -1
print(s)

[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1)) 
from numpy import *
print(sum(range(5),-1)) 

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12968\548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_12968\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [30]:
s = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(s)), s)

array([-6., -1.,  1., -6., -8., -4.,  2., -8., -6.,  6.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
s = np.arange(0, 10)
r = np.arange(5, 15)
np.intersect1d(s, r)


array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [32]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [33]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\Admin\AppData\Local\Temp\ipykernel_12968\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [35]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-11-10
2022-11-11
2022-11-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [36]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [37]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [38]:
s = np.random.uniform(0,10,10)

print (s - s%1)
print (np.floor(s))
print (np.ceil(s)-1)
print (s.astype(int))
print (np.trunc(s))

[7. 6. 3. 7. 9. 7. 7. 5. 4. 4.]
[7. 6. 3. 7. 9. 7. 7. 5. 4. 4.]
[7. 6. 3. 7. 9. 7. 7. 5. 4. 4.]
[7 6 3 7 9 7 7 5 4 4]
[7. 6. 3. 7. 9. 7. 7. 5. 4. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [39]:
s = np.zeros((5,5))
s += np.arange(5)
print(s)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [40]:
def generate():
    for i in range(10):
        yield i
s = np.fromiter(generate(),dtype=float,count=-1)
print(s)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [41]:
s = np.linspace(0,1,11,endpoint=False)[1:]
print(s)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [42]:
s = np.random.random(10)
s.sort()
print(s)

[0.06789825 0.23494091 0.29655641 0.30988631 0.42632013 0.70543231
 0.79031624 0.80179724 0.90122746 0.91762686]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [43]:
s = np.arange(10)
np.add.reduce(s)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [44]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [116]:
a = np.random.random(10)
a.flags.writeable = False
a[0] == 1

False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [46]:
s = np.random.random((10,2))
r,j = s[:,0], s[:,1]
S = np.sqrt(r**2+j**2)
A = np.arctan2(j,r)
print(S)
print(A)

[0.7470126  0.48923654 0.79034489 1.1616534  0.50030647 0.78045932
 0.7353261  0.91427782 1.00039329 0.32623165]
[0.10452508 1.30719874 0.32949211 0.5929299  0.20411501 0.39268539
 0.38535066 0.47586813 0.14071019 0.33322524]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [47]:
s = np.random.random(10)
s[s.argmax()] = 0
print(s)

[0.59270501 0.44778982 0.5425741  0.07983888 0.31693934 0.
 0.6031977  0.24801976 0.27403773 0.21183745]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [48]:
s = np.zeros((5,5), [('x',float),('y',float)])
s['x'], s['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(s)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [49]:
s = np.arange(8)
r = s + 0.5
j = 1.0 / np.subtract.outer(s, r)
print(np.linalg.det(j))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [53]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [108]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [55]:
s = np.arange(100)
r = np.random.uniform(0,100)
index = (np.abs(s-r)).argmin()
print(s[index])

77


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [56]:
s = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(s)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Admin\AppData\Local\Temp\ipykernel_12968\4093601204.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  s = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [57]:
s = np.random.random((10,2))
r,j = np.atleast_2d(s[:,0], s[:,1])
k = np.sqrt( (r-r.T)**2 + (j-j.T)**2)
print(k)

# Much faster with scipy
import scipy

import scipy.spatial

s = np.random.random((10,2))
k = scipy.spatial.distance.cdist(s,s)
print(k)

[[0.         0.50846399 0.41325355 0.30200493 0.30169303 0.60243502
  0.34116358 0.25149557 0.24328818 0.20528071]
 [0.50846399 0.         0.75328665 0.72686948 0.67353045 0.47017803
  0.59004446 0.27381418 0.7491863  0.30868377]
 [0.41325355 0.75328665 0.         0.14998077 0.1116311  0.53361486
  0.74822302 0.49850226 0.36266859 0.48900679]
 [0.30200493 0.72686948 0.14998077 0.         0.08258603 0.60694362
  0.61966806 0.45531821 0.21274608 0.43156595]
 [0.30169303 0.67353045 0.1116311  0.08258603 0.         0.52511305
  0.63707737 0.40809027 0.27732428 0.39200365]
 [0.60243502 0.47017803 0.53361486 0.60694362 0.52511305 0.
  0.87679858 0.41826459 0.7561227  0.46102509]
 [0.34116358 0.59004446 0.74822302 0.61966806 0.63707737 0.87679858
  0.         0.46011508 0.46613604 0.41577909]
 [0.25149557 0.27381418 0.49850226 0.45531821 0.40809027 0.41826459
  0.46011508 0.         0.48275988 0.05012065]
 [0.24328818 0.7491863  0.36266859 0.21274608 0.27732428 0.7561227
  0.46613604 0.482759

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [58]:
s = np.arange(10, dtype=np.int32)
s = s.astype(np.float32, copy=False)
print(s)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [59]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
r = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(r)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_12968\3866841775.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  r = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [60]:
s = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(s):
    print(index, value)
for index in np.ndindex(s.shape):
    print(index, s[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [61]:
s, r = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(s*s+r*r)
sigma, mu = 1.0, 0.0
j = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(j)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [62]:
n = 10
p = 3
s = np.zeros((n,n))
np.put(s, np.random.choice(range(n*n), p, replace=False),1)
print(s)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [63]:
s = np.random.rand(5, 10)

r = s - s.mean(axis=1, keepdims=True)

print(r)

[[ 0.11156318 -0.28145977  0.41269471  0.43867542 -0.49390084 -0.35799742
  -0.16471814  0.35241995 -0.06462688  0.04734979]
 [-0.15953798  0.56725154 -0.33108649 -0.12630226  0.24566829  0.41818101
  -0.02141151 -0.1048506  -0.27201853 -0.21589348]
 [ 0.30491488  0.16669759  0.31809826 -0.50121522 -0.12441681 -0.42602191
   0.05793484 -0.28477318  0.35361095  0.13517061]
 [-0.09035207 -0.04151971 -0.10664113  0.19789407  0.06496892 -0.3135328
   0.21334339 -0.19802477  0.53783695 -0.26397285]
 [-0.27911741 -0.39074701  0.37296419  0.32369342  0.07440295  0.26685245
  -0.12119964 -0.25381964  0.17456544 -0.16759475]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [64]:
s = np.random.randint(0,10,(3,3))
print(s)
print(s[s[:,1].argsort()])

[[8 6 1]
 [9 3 1]
 [0 9 3]]
[[9 3 1]
 [8 6 1]
 [0 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [65]:
s = np.random.randint(0,3,(3,10))
print((~s.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [66]:
s = np.random.uniform(0,1,10)
r = 0.5
j = s.flat[np.abs(s - r).argmin()]
print(j)

0.43009874412373106


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [67]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [68]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

s = NamedArray(np.arange(10), "range_10")
print (s.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [69]:
s = np.ones(10)
I = np.random.randint(0,len(s),20)
s += np.bincount(I, minlength=len(s))
print(s)

np.add.at(s, I, 1)
print(s)

[4. 1. 4. 3. 1. 7. 1. 3. 2. 4.]
[ 7.  1.  7.  5.  1. 13.  1.  5.  3.  7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [70]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [71]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [72]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 57 62 58]
 [60 56 55 56]
 [47 57 48 54]]
[[57 57 62 58]
 [60 56 55 56]
 [47 57 48 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [73]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.46496342 0.45119385 0.49188109 0.63261531 0.45613011 0.4793215
 0.60158335 0.52205847 0.51813836 0.61876224]
0    0.464963
1    0.451194
2    0.491881
3    0.632615
4    0.456130
5    0.479321
6    0.601583
7    0.522058
8    0.518138
9    0.618762
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [74]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.16115196, 0.62957543, 1.2936628 , 0.78572108, 1.52424436])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [75]:
s = np.array([1,2,3,4,5])
rj = 3
ss = np.zeros(len(s) + (len(s)-1)*(rj))
ss[::rj+1] = s
print(ss)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [76]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [77]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [78]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 12) ( 0, 47) ( 0, 72) ( 8, 17) ( 8, 95) (12, 47) (17, 95) (18, 45)
 (18, 99) (23, 31) (23, 63) (23, 78) (23, 96) (30, 56) (30, 68) (31, 78)
 (39, 52) (39, 90) (45, 55) (45, 74) (45, 99) (47, 72) (52, 90) (55, 74)
 (56, 68) (58, 83) (58, 95) (63, 96) (83, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [79]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [80]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
s = np.arange(20)
print(moving_average(s, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [81]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
s = rolling(np.arange(10), 3)
print(s)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [82]:
s = np.random.randint(0,2,100)
np.logical_not(s, out=s)

s = np.random.uniform(-1.0,1.0,100)
np.negative(s, out=s)

array([ 0.92334617,  0.69829443, -0.54565566, -0.94299254, -0.22740283,
        0.3844814 ,  0.20793074, -0.87189043,  0.84840507, -0.41360006,
        0.93563353,  0.43232439, -0.31663404, -0.64499638,  0.27011429,
       -0.06763589,  0.43803648,  0.58303539, -0.87214075, -0.72176063,
       -0.70918811, -0.14527391,  0.89610731, -0.45652188, -0.04720106,
       -0.36024951, -0.14643666, -0.879686  ,  0.12820128,  0.44967295,
       -0.08418809, -0.01756122, -0.40674822,  0.30058318,  0.46754556,
        0.02084126,  0.03257767, -0.41028801, -0.66323998,  0.68933653,
        0.57170919,  0.63116302,  0.95962889, -0.97804757,  0.41313459,
        0.87970824,  0.60668437, -0.71428156, -0.48803249, -0.76694641,
        0.2146491 , -0.15850812, -0.34332212,  0.40175637,  0.9126031 ,
       -0.26995309, -0.49640826,  0.5432399 ,  0.86064584,  0.60708462,
       -0.90797678,  0.38067363, -0.59333397,  0.18148492, -0.10814642,
       -0.9189578 , -0.20229673,  0.56615954, -0.65680729, -0.30

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [83]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.73062603 11.47860938  8.99589512  6.89579492 15.99490514 11.16430293
 10.1483762   2.86226603  5.06250105  4.72271799]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [84]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.10525886  7.01265327  9.23441798  9.10569966  4.85904355  9.10411465
   9.8285557   0.60490764  6.68304275  2.46057852]
 [ 0.66046389  8.72543766  4.86189851  8.31607381  4.28557547 10.73531508
   5.25909638  5.90751281  3.17756572  2.55214491]
 [ 4.4036077   5.8151272   9.68147329  0.84255118  4.39921937  7.59385161
   9.32218096 18.2755579   0.39226955 12.03161941]
 [11.97633768  3.97073506  4.17464823  1.64787708  6.0136497   1.91312228
   5.47050767  1.19578893 15.99422908  7.49552842]
 [ 8.20456     0.46583553  5.81018739  2.50075979  1.80126887  2.53025015
   6.81567506  0.0712031  12.07069083  5.12733992]
 [ 3.33564166 11.5427799   5.29387079 10.6606733   6.69387601 13.54676771
   5.49638952  7.2118688   0.44466895  4.55287475]
 [ 1.14446557  2.9178129   9.02501851  2.72771318  6.39202456  4.7211173
   8.44685942 15.86329093  3.64063678  9.07258156]
 [ 9.76868249  3.10444901  1.30656406  2.36100731  6.5923193   1.09914865
   2.49168426  2.12493315 13.96003434  4.4224518 ]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [85]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 8 6 1 4 0 3 5 1 5]
 [2 2 6 8 0 1 8 1 5 6]
 [0 5 3 3 0 1 6 5 8 7]
 [0 7 1 9 1 8 0 2 1 1]
 [9 7 8 9 9 7 3 2 3 5]
 [5 4 5 5 0 3 6 3 8 1]
 [2 5 1 0 2 4 2 1 9 8]
 [9 7 3 2 2 0 0 0 0 9]
 [1 6 5 7 8 0 1 8 9 6]
 [2 0 2 1 5 6 5 5 8 8]]
[[0 0 0 0 0]
 [0 8 8 6 1]
 [0 2 2 6 8]
 [0 0 5 3 3]
 [0 0 7 1 9]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_12968\1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [86]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [87]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [88]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [89]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 2]
   [4 0 3]
   [3 4 0]]

  [[4 2 2]
   [0 3 3]
   [4 0 1]]

  [[2 2 2]
   [3 3 0]
   [0 1 2]]

  [[2 2 1]
   [3 0 3]
   [1 2 3]]

  [[2 1 1]
   [0 3 3]
   [2 3 1]]

  [[1 1 2]
   [3 3 2]
   [3 1 0]]

  [[1 2 2]
   [3 2 2]
   [1 0 1]]

  [[2 2 2]
   [2 2 1]
   [0 1 2]]]


 [[[4 0 3]
   [3 4 0]
   [2 4 2]]

  [[0 3 3]
   [4 0 1]
   [4 2 0]]

  [[3 3 0]
   [0 1 2]
   [2 0 1]]

  [[3 0 3]
   [1 2 3]
   [0 1 2]]

  [[0 3 3]
   [2 3 1]
   [1 2 2]]

  [[3 3 2]
   [3 1 0]
   [2 2 2]]

  [[3 2 2]
   [1 0 1]
   [2 2 3]]

  [[2 2 1]
   [0 1 2]
   [2 3 3]]]


 [[[3 4 0]
   [2 4 2]
   [1 0 3]]

  [[4 0 1]
   [4 2 0]
   [0 3 4]]

  [[0 1 2]
   [2 0 1]
   [3 4 0]]

  [[1 2 3]
   [0 1 2]
   [4 0 4]]

  [[2 3 1]
   [1 2 2]
   [0 4 3]]

  [[3 1 0]
   [2 2 2]
   [4 3 2]]

  [[1 0 1]
   [2 2 3]
   [3 2 3]]

  [[0 1 2]
   [2 3 3]
   [2 3 3]]]


 [[[2 4 2]
   [1 0 3]
   [1 2 3]]

  [[4 2 0]
   [0 3 4]
   [2 3 0]]

  [[2 0 1]
   [3 4 0]
   [3 0 4]]

  [[0 1 2]
   [4 0 4]
   [0 4 2]]

  [[1 2 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [90]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 16 15 15  5]
 [16  9  9 14  8]
 [15  9  3 42  1]
 [15 14 42  8 12]
 [ 5  8  1 12  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [91]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [92]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [93]:
def iterate(Z):
  
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])


    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [94]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9996 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [95]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [96]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [107]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.83 s ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
633 ms ± 28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
366 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [103]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [98]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 1 1]
 [1 1 4]
 [0 2 4]
 [2 4 0]
 [0 2 3]
 [1 1 4]
 [4 0 4]
 [0 1 1]
 [1 1 3]
 [2 4 2]]
[[2 1 1]
 [1 1 4]
 [0 2 4]
 [2 4 0]
 [0 2 3]
 [1 1 4]
 [4 0 4]
 [0 1 1]
 [1 1 3]
 [2 4 2]]
[[2 1 1]
 [1 1 4]
 [0 2 4]
 [2 4 0]
 [0 2 3]
 [1 1 4]
 [4 0 4]
 [0 1 1]
 [1 1 3]
 [2 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [99]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [100]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [101]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)      
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)   

array([[0.24716256, 0.37319229, 0.007492  , 0.02167422, 0.39234396,
        0.41578645, 0.09846096, 0.31535976, 0.41558485, 0.37731672],
       [0.48864796, 0.7378126 , 0.01481192, 0.0428506 , 0.77567604,
        0.82202257, 0.19466035, 0.62347591, 0.82162399, 0.74596673],
       [0.37606677, 0.56782556, 0.01139935, 0.03297811, 0.59696552,
        0.63263412, 0.14981192, 0.47983127, 0.63232737, 0.57410104],
       [0.44418574, 0.67067881, 0.01346418, 0.03895161, 0.70509704,
        0.74722649, 0.17694814, 0.56674565, 0.74686417, 0.678091  ],
       [0.51299223, 0.77457017, 0.01554984, 0.0449854 , 0.81431994,
        0.86297545, 0.20435826, 0.65453726, 0.86255701, 0.78313053],
       [0.34298466, 0.51787467, 0.01039657, 0.03007707, 0.54445122,
        0.57698211, 0.13663315, 0.43762113, 0.57670234, 0.5235981 ],
       [0.0936959 , 0.14147202, 0.00284011, 0.0082164 , 0.14873215,
        0.15761887, 0.03732519, 0.11954851, 0.15754245, 0.14303553],
       [0.27923741, 0.4216223 , 0.0084642

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [104]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [105]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [106]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22950931  0.16327094]
